---
- name: Generate services for prometheus and alerts
  template: src=service.j2 dest={{mktemp.stdout}}/templates/{{obj_name}}-svc.yaml
  vars:
    obj_name: "{{item}}"
    ports:
    - name: "{{obj_name}}"
      port: 443
      protocol: TCP
      targetPort: 8443
    selector:
      app: "{{obj_name}}"
    labels:
      name: "{{obj_name}}"
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: "{{obj_name}}-tls"
  with_items:
    - prometheus
    - alerts
  changed_when: no

- name: Generate service for alertmanager
  template: src=service.j2 dest={{mktemp.stdout}}/templates/{{obj_name}}-svc.yaml
  vars:
    obj_name: alertmanager
    ports:
    - name: "{{obj_name}}"
      port: 9093
      protocol: TCP
      targetPort: 9093
    selector:
      app: alerts
    labels:
      name: "{{obj_name}}"
  changed_when: no
