---
- name: Generate deployment for alertmanager behind message-buffer behind oauth-proxy
  template: src=deployment.j2 dest={{mktemp.stdout}}/templates/{{obj_name}}-deployment.yaml
  vars:
    obj_name: alerts
    namespace: "{{ openshift_prometheus_namespace }}"
    replicas: 1
    service_account_name: prometheus
    containers:
    - name: oauth-proxy
      image: "{{ openshift_prometheus_image_proxy }}"
      ports:
      - containerPort: 8443
        name: web
      args:
      - -https-address=:8443
      - -email-domain=*
      - -client-id=system:serviceaccount:{{ openshift_prometheus_namespace }}:prometheus
      - -upstream=http://localhost:9099
      - -provider=openshift
      - -redirect-url=https:///oauth2/callback
      - '-openshift-sar={"namespace": "{{ openshift_prometheus_namespace }}", "verb": "list", "resource": "services"}'
      - -tls-cert=/etc/tls/private/tls.crt
      - -tls-key=/etc/tls/private/tls.key
      - -client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token
      - -cookie-secret-file=/etc/proxy/secrets/session_secret
      - -skip-auth-regex=^/metrics
      - '-openshift-delegate-urls={"/": {"resource": "namespaces", "verb": "get", "name": "{{ openshift_prometheus_namespace }}" }}'
      mounts:
      - path: /etc/tls/private
        name: alerts-tls
      - path: /etc/proxy/secrets
        name: secrets

    - name: message-buffer
#      args:
      image: "{{ openshift_prometheus_image_message_buffer }}"
      mounts:
      - path: /message-buffer
        name: message-buffer-data
      ports:
      - containerPort: 9099
        name: message-buf

    - name: alertmanager
      args:
      - -config.file=/etc/alertmanager/alertmanager.yml
      image: "{{ openshift_prometheus_image_alertmanager }}"
      ports:
      - containerPort: 9093
        name: web
      mounts:
      - path: /etc/alertmanager
        name: alertmanager-config
      - path: /alertmanager
        name: alertmanager-data

    volumes:
    - configMap:
        defaultMode: 420
        name: alertmanager
      name: alertmanager-config
    - name: secrets
      secret:
        secretName: alerts-proxy
    - name: alerts-tls
      secret:
        secretName: alerts-tls
    - emptyDir: {}
      name: alertmanager-data
    - emptyDir: {}
      name: message-buffer-data #TODO: make persistent
  changed_when: no

