---
- name: Generating serviceaccounts for prometheus
  template: src=serviceaccount.j2 dest={{mktemp.stdout}}/templates/prometheus-{{obj_name}}-sa.yaml
  vars:
    obj_name: "{{item.name}}"
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"{{item.name}}"}}'
    secrets:
    - "{{item.secret}}"
  with_items:
  - name: prometheus
    secret: prometheus-secrets
  changed_when: no
