---
- name: generate prometheus and alert proxy secret template
  template:
    src: secret_template.j2
    dest: "{{ mktemp.stdout }}/templates/{{ item }}-secret.yaml"
  vars:
    name: "{{ item }}-proxy"
    namespace: "{{ openshift_prometheus_namespace }}"
    session_secret: "{{ 43 | oo_random_word }}"
  with_items:
    - prometheus
    - alerts
  changed_when: no
