---
- name: generate prometheus and alert proxy secret template
  template:
    src: secret_template.j2
    dest: "{{ tempdir }}/templates/{{ item }}-secret.yaml"
  vars:
    name: "{{ item }}-proxy"
    namespace: "{{ openshift_prometheus_namespace }}"
    session_secret: "{{ 43 | oo_random_word }}"
  with_items:
    - prometheus
    - alerts
  changed_when: no

- name: Create {{ item }} secret
  oc_obj:
    state: present
    name: "{{ item }}-proxy"
    kind: secret
    namespace: "{{ openshift_prometheus_namespace }}"
    files:
    - "{{ tempdir }}/templates/{{ item }}-secret.yaml"
    delete_after: true
  with_items:
    - prometheus
    - alerts

