---

- name: Generate Prometheus deployment and configMap
  include: "{{ role_path }}/tasks/generate_{{ include_file_prom }}.yaml"
  with_items:
    - prometheus_deployment
    - prometheus_configmap
  loop_control:
    loop_var: include_file_prom
