---
# tasks file for openshift_prometheus

#- name: Gather OpenShift Prometheus Facts
#  openshift_prometheus_facts:
#    oc_bin: "{{openshift.common.client_binary}}"
#    openshift_prometheus_namespace: "{{openshift_prometheus_namespace}}"

- name: Add prometheus project
  oc_project:
    state: present
    name: "{{ openshift_prometheus_namespace }}"
    description: Prometheus

- name: generate prometheus deployment
  template:
    src: prometheus.j2
    dest: "{{ prometheus_template_path }}"
  vars:
    namespace: "{{openshift_prometheus_namespace}}"
    image_proxy: "openshift/oauth-proxy:v1.0.0"
    image_prometheus: "openshift/prometheus:v2.0.0-dev"
    image_alertmanager: "prom/alertmanager"
    image_message_buffer: "ilackarms/message-buffer"
  register: result

- debug: var=result

- name: Deploying template
  command: >
    {{ openshift.common.client_binary }} --config={{ kubeconfig }}
    new-app -f {{ prometheus_template_path }}
    -n {{ openshift_prometheus_namespace }}
  register: template_deplyment
  failed_when: "'error' in template_deplyment.stderr"

- debug: var=template_deplyment
