---

- name: Create temp directory for doing work in on target
  command: mktemp -td openshift-prometheus-ansible-XXXXXX
  register: mktemp
  changed_when: False

- set_fact:
    tempdir: "{{ mktemp.stdout }}"

- name: Create templates subdirectory
  file:
    state: directory
    path: "{{ tempdir }}/templates"
    mode: 0755
  changed_when: False

# not sure i need this
- name: Copy the admin client config(s)
  command: >
     cp {{ openshift.common.config_base}}/master/admin.kubeconfig {{ tempdir }}/admin.kubeconfig
  changed_when: False
  check_mode: no
  tags: prometheus_init
  when: False

- include: "{{ (openshift_prometheus_install_prometheus | bool) | ternary('install_prometheus.yaml','uninstall_prometheus.yaml') }}"

- name: Delete temp directory
  file:
    name: "{{ tempdir }}"
    state: absent
  changed_when: False
  when: False
